services:
    # User API service
    user-api:
        container_name: lunarflow-user-api
        build:
            context: src/main/docker
            dockerfile: Dockerfile.dev
        ports:
            - "5000:8080" # Application port
            - "5005:5005" # Java debugging port
        restart: always
        volumes:
            - ./:/work/
        command: ["./mvnw", "quarkus:dev", "-Dkc-admin-client.version=${KC_ADMIN_CLIENT_VERSION}"]
        environment:
            # Point to your external Keycloak instance
            - QUARKUS_OIDC_AUTH_SERVER_URL=http://keycloak.luxdomain.lan/realms/eclipse
            - QUARKUS_OIDC_CLIENT_ID=lunarflow
            - QUARKUS_OIDC_CREDENTIALS_SECRET=bLANAvDIeRmlTfCI2JKnMOgz862UmQED
            # Add CORS settings for working with external services
            - QUARKUS_HTTP_CORS=true
            - QUARKUS_HTTP_CORS_ORIGINS=*            