services:
    # User API service
    user-api:
        container_name: lunarflow-user-api
        build:
            context: src/main/docker
            dockerfile: Dockerfile.dev
        ports:
            - "5000:8080" # Application port
            - "5005:5005" # Java debugging port
        restart: always
        volumes:
            - ./:/work/
        command: ["./mvnw", "quarkus:dev"]
        environment:
            # Point to your external Keycloak instance
            - QUARKUS_OIDC_AUTH_SERVER_URL=${QUARKUS_OIDC_AUTH_SERVER_URL}
            - QUARKUS_OIDC_CLIENT_ID=${QUARKUS_OIDC_CLIENT_ID}
            - QUARKUS_OIDC_CREDENTIALS_SECRET=${QUARKUS_OIDC_CREDENTIALS_SECRET}    